### ISSUE TITLE
[bug] audio quality is choppy on some games when interacting with controls

### ISSUE THREAD

**Issue by thenick775** [thenick775/gbajs3#138]
### Discussed in https://github.com/thenick775/gbajs3/discussions/136

<div type='discussions-op-text'>

<sup>Originally posted by **sonht0555** June 24, 2024</sup>
@thenick775 I'm trying to play the game Earthbound [1-2].gba.  The audio experience is having problems. Every time I touch the screen, there is a "popping" noise like a slight audio noise.  You can try wearing headphones and playing a few games, sometimes the sound will be interrupted, before using Module.setFastForwardMultiplier() this error did not appear.</div>

This is a known problem with mGBA, but I feel that having what we do currently on the main thread is also exacerbating the problem.

Some potential options to explore:
- fully thread the emulator core itself
   - move audio to an audio worklet off the main thread
- debounce control interactions

**Comment by thenick775** [comment]
Note: this appears to be a regression occurring during/sometime after #120

**Comment by PeachByMilk** [comment]
In some Pokémon games, this becomes more noticeable.

**Comment by thenick775** [comment]
@PeachByMilk which games in particular?

I'm not hearing the best, but inclement emerald does have a lot of sharp tones.

Earthbound appears to be another good one to reproduce.

Good news is I should be able to fix this in the [mGBA core](https://github.com/thenick775/mgba/tree/feature/wasm) relatively soon 😎

**Comment by PeachByMilk** [comment]
@thenick775  Thanks for addressing the issue! Looking forward to the updates! 😊

**Comment by PeachByMilk** [comment]
Just to note, the audio tends to pop at the start and crackles during fast-forwarding.

**Comment by thenick775** [comment]
Yeah some of that can be fixed on startup potentially.

But when fast forward is active, I consider that a non-issue, at least for now.

That is a much harder problem to solve.

**Comment by thenick775** [comment]
@PeachByMilk I've just merged a fix that should help to reduce the issue, let me know if you see the same 😎

I recommend opening in a private or refresh a few times, so that you pick up the latest version through the service worker.

**Comment by PeachByMilk** [comment]
nice! The problem is solved, but it will freeze in low power mode.

**Comment by thenick775** [comment]
@PeachByMilk can you attach a video of what you're seeing?

I don't see the same.

**Comment by thenick775** [comment]
If your backgrounding the app, then this is expected.

You can't resume the audio playback without a user interaction, and instead of a body listener, I elected to make the user adjust the volume instead.

Maybe its time to revisit that decision 😎
