### ISSUE TITLE
Emulator not loading save files unless if its at the beginning of the game.

### ISSUE THREAD

**Issue by preston7363** [thenick775/gbajs3#160]
I logged off of pokemon LeafGreen for the day and saved and downloaded the save. The next day I accidentally load the wrong save files and tried to change it, but when I did, it just told me to make a new playthrough. Only the save at the beginning of the game works. All others don't. Please help me. thanks

**Comment by thenick775** [comment]
Curious on your workflow, did you only save in game?

Did you save your file system in the 'File System' modal?

**Comment by preston7363** [comment]
Yes I saved ingame and saved the file system aswell. I uploaded it in the pre-game actions aswell but it just asks me to start a new game.

**Comment by preston7363** [comment]
Hey! I figured out the problem. Basically, since I had multiple save files with the same name, my computer would automatically add a number to the end of the file name each time I added a file with the same name. For some reason, the emulator can't read the file with the numbers. For example, it would be able to read: "LeafGreen.sav", and not: "LeafGreen (12).sav". Maybe this is a bug you could fix. Thanks!

**Comment by thenick775** [comment]
Ahh yes! For mGBA you must have the same file name exactly the same as the ROM name for it to be loaded automatically 😎

**Comment by thenick775** [comment]
I don't know if I have the time to investigate doing something like that now, but since the gbaJS core (when it existed) was able to reconcile separate save names, I might be able to do the same.

If your ROM had the (1) etc. at the end things would have also loaded. This might be something to add when other cores are roped into the mix.

I think for now adding documentation/tour items to cover this would be best 😎

**Comment by thenick775** [comment]
One thing to note, if you save in the file system menu item, you don't need to download your save and reupload it.

It will be stored in your browsers indexeddb, ready for you when you run the ROM the next time.

**Comment by preston7363** [comment]
Alright thanks!

**Comment by thenick775** [comment]
@preston7363 I've added some tour text covering this topic, see: #161 🚀
