### ISSUE TITLE
Add how to use interface

### ISSUE THREAD

**Issue by HedgyhogGuy** [thenick775/gbajs3#188]
I wanted to know if there was a way you can tell the user how saving works. I thought you had to use save states, but it turns out that it uses browser storage, so I thought that I lost all my progress (thanks for adding that though, it's great). I just think an explanation would make things easier and making the save message on by default.

**Comment by thenick775** [comment]
I think this is a great idea, for some clarification, are you referring to:
- using the file system modal as a user to save states
- the difference between save states and save files
- where the files are saved and how they are retrieved/persisted

I'd be happy to add some docs in the [Wiki](https://github.com/thenick775/gbajs3/wiki), as well as some additional product tour items!

**Comment by thenick775** [comment]
I've made some additions to the WIKI [here](https://github.com/thenick775/gbajs3/wiki/Getting-Started#saving-the-file-system) describing how the file system works a bit more in depth.

Additionally, I've made the default ENABLED for saving the file system on in game saves 😎 This setting can be accessed through the file system modal if you need to adjust it.

Let me know if you have any other requests or ideas for clarity on how file system operations work!
