### ISSUE TITLE
Issue Uploding

### ISSUE THREAD

**Issue by Sese41** [thenick775/gbajs3#207]
When I closed the tab and went back I couldn't upload the ROM anymore.

**Comment by thenick775** [comment]
Do you have any screenshots or a video?

What device and browser are you using?

Are you installed as a PWA?

Will try to investigate with the information I currently have!

**Comment by thenick775** [comment]
Based on your initial description I have performed the following test, I am able to repeatedly upload rom files as expected:

https://github.com/user-attachments/assets/2f49e900-f880-4ba2-b22d-6104001b37a9
