### ISSUE TITLE
Awesome Job!

### ISSUE THREAD

**Issue by hunter1026** [thenick775/gbajs3#30]
i love this web based gba emulator on my iphone. but theres one thing that bugs me is that when i move or resize things like the virtual controls and the screen, etc, when i close the web app and open it back up everything is reset back to original. can you make it to where it saves our options for when we move and resize things..i have it installed onto my homescreen.

**Comment by thenick775** [comment]
Thank you for opening this issue!

This particular item is on my roadmap in the near future, and should be completed here by end of year at the latest.
But I'll bump this feature to the top of the queue! 😎

**Comment by thenick775** [comment]
@hunter1026 I've deployed a version allowing you to save/reset the positions of every movable element.

Let me know if the suits your needs!
