### ISSUE TITLE
Setup

### ISSUE THREAD

**Issue by Qinx99** [thenick775/gbajs3#32]
Hello! I'm interested in setting up my own one but I don't really get of how to set up all the files.

**Comment by thenick775** [comment]
What steps have you tried from the README getting started section?

Additionally, as a part of this issue I'll make that README section a bit more clear.

**Comment by thenick775** [comment]
@Qinx99 I've made a pr that addresses the setup instructions.

Feel free to let me know if this is not sufficient for local builds!

If you require hosting advice, you'll have to learn how to setup a server in a provider of your choice, like AWS/Azure and then follow the install instructions there.

For hosting your own instance, you will need a domain and real certificates through services like lets encrypt and a domain provider of your choice.
