### ISSUE TITLE
How do I load my save download?

### ISSUE THREAD

**Issue by Slice1963** [thenick775/gbajs3#34]
I saved the state and then downloaded the save. I then uploaded the save and the same ROM, but I don't know how to load the save from there. Is it in the File System?

**Comment by thenick775** [comment]
If your save/rom are available to the emulator they will be in the `File System` modal.

If your save file is there, it will load automatically when you boot a rom file with the same name!

**Comment by thenick775** [comment]
You file system would look like this if it has saves and rom files available:

<img width="300" alt="Screenshot 2023-12-22 at 5 56 14 PM" src="https://github.com/thenick775/gbajs3/assets/40526638/f0ed3d03-3829-4fd5-b790-82b78d12d8a1">


Then for example, you would load your rom file through the `Upload Rom` modal.

If you save your `File System` after this, then you can load games through the `Load Local Rom` modal.

**Comment by Slice1963** [comment]
Thank you! My saves are working now!

**Comment by thenick775** [comment]
Awesome to hear, thank you for opening this issue! 😎
