### ISSUE TITLE
using "mgba-emualtor" in node environment

### ISSUE THREAD

**Issue by ggomaeng** [thenick775/gbajs3#74]
Hi! This is an awesome project :) kudos to the creator(s).

I'm trying to run the emulator/mgba in a node environment. Is it possible?

Thanks in advance!

**Comment by thenick775** [comment]
What are you attempting to run or interact with exactly?

I believe the emulator web assembly file itself requires the browser to use.

**Comment by ggomaeng** [comment]
Hey! Thanks for the prompt response. I should have provided more context. 

So there is this social media app called "Warpcast", and people are able to interact with content through something called "frames". 

![image](https://github.com/thenick775/gbajs3/assets/18402191/252e20b4-7c3e-4bff-94c5-f9571a87a717)

I wanted to do a little side project where users will be able to play pokemon through frames.

I need this to be rendered serverside since the images shown through frames are delivered through metatags.

So an example flow would be
1. user clicks up button on the frame
2. simulate up button serverside
3. draw the next frame on emulator
4. deliver content

--- 

What I've tried so far
I've tried doing this on Next.js using Cairo's Canvas module & converting web related code like FileReader to node FS. 

I think I was able to load the mgba.js but couldn't get the game to run through the loadGame method.

Do I pass the path to the rom file? Or do I pass a buffer stream?

Thanks in gbadvance!! 😉

**Comment by ggomaeng** [comment]
@thenick775 Here are some changes I made:

1. load wasm file from the public folder
```ts

function instantiateAsync(binary, binaryFile, imports, callback) {
      if (
        !binary &&
        typeof WebAssembly.instantiateStreaming == "function" &&
        !isDataURI(binaryFile) &&
        typeof fetch == "function"
      ) {
        return fetch("http://localhost:3000/mgba.wasm", {
          credentials: "same-origin",
        }).then((response) => {
          var result = WebAssembly.instantiateStreaming(response, imports);
          return result.then(callback, function (reason) {
            err(`wasm streaming compile failed: ${reason}`);
            err("falling back to ArrayBuffer instantiation");
            return instantiateArrayBuffer(binaryFile, imports, callback);
          });
        });
      }
      return instantiateArrayBuffer(binaryFile, imports, callback);
    }

2. load emulator using cairo canvas

```ts
import { createCanvas } from "canvas";
import { mGBAEmulator } from "./mgba/mgba-emulator";
import mGBA from "./mgba/wasm/mgba";

export async function getGameBoy() {
  const canvas = createCanvas(240, 160);
  const context = canvas.getContext("2d");
  if (context) {
    context.imageSmoothingEnabled = false;
  }
  const module = await mGBA({ canvas: canvas as any });
  const emulator = mGBAEmulator(module);
  return { emulator, canvas, context };
}

```

3. Trying to load rom

```ts
const root = process.cwd();
const { emulator, canvas } = await getGameBoy();
const success = emulator.run(`${root}/data/games/pokemon-gold.gbc`);
console.log({ success, emulator });
```

<img width="552" alt="image" src="https://github.com/thenick775/gbajs3/assets/18402191/8f2eb2a5-9159-4138-8ae7-78e7df8689c5">

**Comment by thenick775** [comment]
To answer some questions:

To use the `loadGame` method on the mGBA module, you'll want to pass the path of the game relative to the mGBA internal file system provided by emscripten. In short, the full path as viewed by mGBA.

In short, you'll want to upload a javascript `File` object to the mGBA FS (handled with SDL2 and emscripten) and then load the game using the provided paths and the rom name.

I'm not too clear on the limitations you have from being server side, but something like this may work:
```
const runCallback = () => {
  const hasSucceeded = mGBA.loadGame(
    mGBA.filePaths().gamePath + '/' + yourFile.name
  );
  if (hasSucceeded) {
    console.log('game is running');
  }
};
mGBA.uploadRom(yourFile, runCallback);
```
where `mGBA` is your loaded wasm module with a provided canvas, and `yourFile` is your rom as a file object.

I also don't think cairo has `webgl` canvas context support, which emscripten is using to power the canvas rendering opaque to the frontend you see here. I've looked around a bit and it seems `fabric.js` may have the tooling you need, but I don't think your canvas will be able to show the contents of the canvas buffers otherwise (though it may work 🤷, I don't really know).

**Comment by thenick775** [comment]
Additionally, I'd recommend attempting to use the emscripten FS to initialize where your going to put your games:
```
mGBA.FS.mkdir('/data/games');
```

**Comment by ggomaeng** [comment]
Will give it a shot and keep you updated! :-) 

If you don't mind, do you have any channel I can DM you - maybe like discord?

Conversating here is fine too!

**Comment by thenick775** [comment]
But if you can't get anything working, feel free to get a dockerfile setup along with your source code as an example, I'd be happy to take a deeper look if we have a common image/tooling to work with

**Comment by thenick775** [comment]
But in reference to a channel, feel free to create a discussion [here](https://github.com/thenick775/gbajs3/discussions)!

**Comment by ggomaeng** [comment]
> But if you can't get anything working, feel free to get a dockerfile setup along with your source code as an example, I'd be happy to take a deeper look and fool around a bit if we have a common image/tooling/example to work with

for sure :) thanks for the helping hand

**Comment by thenick775** [comment]
But an ideal full example if your module is correctly loaded would tentatively be:
```
...
// initialize emulator with your canvas
const mGBA = await mGBA({ canvas });

// attempt to initialize file system using FSInit
await mGBA.FSInit();

// setup a callback to run the rom and log the results
const runCallback = () => {
  const hasSucceeded = mGBA.loadGame(
    mGBA.filePaths().gamePath + '/' + yourFile.name
  );
  if (hasSucceeded) {
    console.log('game is running');
  } else{
    console.log('running game has failed');
  }
};

// upload rom which will run the above callback if successful
mGBA.uploadRom(yourFile, runCallback);
```

**Comment by thenick775** [comment]
Just circling back around to this topic, I'm going to close this issue as I believe it may be more appropriate to open one in my [mGBA fork](https://github.com/thenick775/mgba) if any active dev work is needed.

Feel free to open a discussion here or in the repo above, or continue to comment in this issue if you have any issues getting the emulator binary running in a way that supports your project 😎

**Comment by thenick775** [comment]
Hey hey @ggomaeng I think I may have some answers after playing around with this a bit more.

My mGBA [fork](https://github.com/thenick775/mgba) is currently compiled to only work in a web and worker context per emscripten [docs](https://emscripten.org/docs/optimizing/Optimizing-Code.html#miscellaneous-code-size-tips) on optimization.

You should be able to change this to support node by modifying this [line](https://github.com/thenick775/mgba/blob/feature/wasm/src/platform/wasm/CMakeLists.txt#L8) in the compilation command to support a node.js environment, where I think you'll have far less problems if it doesn't have problems compiling using the readme instructions!
