### ISSUE TITLE
Hosting with Github Pages

### ISSUE THREAD

**Issue by 7v5** [thenick775/gbajs3#79]
Would it be possible to create a fork of gbajs3 and host it using github pages? I'm not entirely sure if github pages would be capable of storing things such as locally loaded roms and/or save states.

**Comment by thenick775** [comment]
It's definitely doable, I've implemented everything necessary for this in #49, with the exception of loading a rom from an external URL through query params.

**Comment by thenick775** [comment]
You'll see some other details there, but you'll have to work out the pipeline and how y out want to publish the static assets

**Comment by thenick775** [comment]
I'll see if I can get the artifacts setup in a way to make this easy for anyone wanting to deploy through ghp 😎

**Comment by 7v5** [comment]
Thanks! If you can get it set up so its easy to understand/do it would be greatly appreciated.

**Comment by thenick775** [comment]
Just a note, are you trying to host the backend server(s) at all?

Do you want to deploy the frontend with GHP, but the backend somewhere else?

It might just be worth it to go to my hosted page instance if all you want is the frontend.

I'm still planning to make a manual action available to deploy to GHP, but I don't really see any gains from that in what I think is your current use case for self hosting.

**Comment by 7v5** [comment]
I just wanted to host it myself so I could use the account system properly, as I use a variety of devices and I would like to be able to play on the same save file between all of them without the use of storing the save in google drive each time etc.

I can deploy the backend servers with google cloud, but I'm not entirely sure how I would do this, but Im sure I could figure it out.

**Comment by thenick775** [comment]
You could also split this off to host the frontend in GitHub pages, but I haven't worked out build with environment variables yet.

Unfortunately you'd still need to host the backend somewhere to reap those gains, I know Vercel can host both front/backend items, but that is what I build the NGINX webserver for when hosting in a non-static environment.

So my recommendation would be to get a server/ssl certs setup as shown above, and then use docker to deploy your hosted instance.

**Comment by 7v5** [comment]
Is it 100% necessary to get SLL certificates? I don't have a domain and have just been using http://*ip address*. AFAIK CertBot doesnt give SLL certs for bare ip addresses

**Comment by thenick775** [comment]
You can build self signed certs, but for the backend currently it's required to at least have them.

I'd try https://zerossl.com, but this may be a good enhancement to consider for the backend.

Issues are that iOS requires valid https traffic if I remember correctly, or else nothing works.

**Comment by 7v5** [comment]
Im using digital ocean now, and I'm a little confused. Ive installed docker properly, do I need to install nginx too? Also, I cant find any .env inside of /root/gbajs3/docker. I only see docker-compose.yaml, and a subdirectory named server when i use ls.

**Comment by thenick775** [comment]
> Im using digital ocean now, and I'm a little confused. Ive installed docker properly, do I need to install nginx too? Also, I cant find any .env inside of /root/gbajs3/docker. I only see docker-compose.yaml, and a subdirectory named server when i use ls.
> 
> 
> 
> Edit: I figured it out, just had to use 'ls -a'. 

You shouldn't need to install nginx, that will get assembled when using docker compose!

**Comment by thenick775** [comment]
It could be that where your trying to build the images doesn't have enough CPU.

Try with something like this:
```
docker-compose down && \
docker system prune -a && \
docker-compose --parallel 2 up --build -d && \
docker rmi $(docker images -f "dangling=true" -q) && \
docker system prune;
```

**Comment by thenick775** [comment]
The go binaries usually take a minute each to build on my current server setup (unless I pull them from a private docker registry and build ahead of time).

**Comment by thenick775** [comment]
You could also build the docker tar files on your local machine, and upload them to your server, import them to docker, and then run the images as a nuclear option.

**Comment by 7v5** [comment]
It could definitely be because I don't have enough cpu, I am using the cheapest server on digital ocean.

**Comment by 7v5** [comment]
Hey, I tried pasting the command you gave me into the SSH terminal but it says docker-compose command isnt found

**Comment by 7v5** [comment]
[+] Running 1/4
 ✔ Network docker_default               Created                                                                    0.1s
 ⠙ Container docker-gba-postgres-1      Created                                                                    0.1s
 ⠋ Container docker-gba-auth-server-1   Created                                                                    0.1s
 ⠋ Container docker-gba-admin-server-1  Created                                                                    0.1s
 ⠋ Container docker-webserver-1         Created                                                                    0.0s
Attaching to gba-admin-server-1, gba-auth-server-1, gba-postgres-1, webserver-1
gba-postgres-1      | The files belonging to this database system will be owned by user "postgres".
gba-postgres-1      | This user must also own the server process.
gba-postgres-1      |
gba-postgres-1      | The database cluster will be initialized with locale "en_US.utf8".
gba-postgres-1      | The default database encoding has accordingly been set to "UTF8".
gba-postgres-1      | The default text search configuration will be set to "english".
gba-postgres-1      |
gba-postgres-1      | Data page checksums are disabled.
gba-postgres-1      |
gba-postgres-1      | fixing permissions on existing directory /var/lib/postgresql/data ... ok
gba-postgres-1      | creating subdirectories ... ok
gba-postgres-1      | selecting dynamic shared memory implementation ... posix
gba-postgres-1      | selecting default max_connections ... 100
gba-postgres-1      | selecting default shared_buffers ... 128MB
gba-postgres-1      | selecting default time zone ... UTC
gba-postgres-1      | creating configuration files ... ok
gba-postgres-1      | running bootstrap script ... ok
gba-postgres-1      | sh: locale: not found
gba-postgres-1      | 2024-04-19 01:13:41.742 UTC [31] WARNING:  no usable system locales were found
gba-postgres-1      | performing post-bootstrap initialization ... ok
gba-postgres-1      | syncing data to disk ... ok
gba-postgres-1      | initdb: warning: enabling "trust" authentication for local connections
gba-postgres-1      | initdb: hint: You can change this by editing pg_hba.conf or using the option -A, or --auth-local and --auth-host, the next time you run initdb.
gba-postgres-1      |
gba-postgres-1      |
gba-postgres-1      | Success. You can now start the database server using:
gba-postgres-1      |
gba-postgres-1      |     pg_ctl -D /var/lib/postgresql/data -l logfile start
gba-postgres-1      |
gba-postgres-1      | waiting for server to start....2024-04-19 01:13:42.515 UTC [37] LOG:  starting PostgreSQL 15.2 on x86_64-pc-linux-musl, compiled by gcc (Alpine 12.2.1_git20220924-r4) 12.2.1 20220924, 64-bit
gba-postgres-1      | 2024-04-19 01:13:42.518 UTC [37] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
gba-postgres-1      | 2024-04-19 01:13:42.525 UTC [40] LOG:  database system was shut down at 2024-04-19 01:13:42 UTC
gba-postgres-1      | 2024-04-19 01:13:42.532 UTC [37] LOG:  database system is ready to accept connections
gba-postgres-1      |  done
gba-postgres-1      | server started
gba-postgres-1      | CREATE DATABASE
gba-postgres-1      |
gba-postgres-1      |
gba-postgres-1      | /usr/local/bin/docker-entrypoint.sh: running /docker-entrypoint-initdb.d/init_admin_db.sql
gba-postgres-1      | SET
gba-postgres-1      | SET
gba-postgres-1      | SET
gba-postgres-1      | SET
gba-postgres-1      | SET
gba-postgres-1      |  set_config
gba-postgres-1      | ------------
gba-postgres-1      |
gba-postgres-1      | (1 row)
gba-postgres-1      |
gba-postgres-1      | SET
gba-postgres-1      | SET
gba-postgres-1      | SET
gba-postgres-1      | SET
gba-postgres-1      | CREATE SEQUENCE
gba-postgres-1      | ALTER TABLE
gba-postgres-1      | SET
gba-postgres-1      | SET
gba-postgres-1      | CREATE TABLE
gba-postgres-1      | ALTER TABLE
gba-postgres-1      | CREATE SEQUENCE
gba-postgres-1      | ALTER TABLE
gba-postgres-1      | CREATE TABLE
gba-postgres-1      | ALTER TABLE
gba-postgres-1      | CREATE SEQUENCE
gba-postgres-1      | ALTER TABLE
gba-postgres-1      | CREATE TABLE
gba-postgres-1      | ALTER TABLE
gba-postgres-1      | CREATE TABLE
gba-postgres-1      | ALTER TABLE
gba-postgres-1      | CREATE TABLE
gba-postgres-1      | ALTER TABLE
gba-postgres-1      | CREATE TABLE
gba-postgres-1      | ALTER TABLE
gba-postgres-1      | CREATE SEQUENCE
gba-postgres-1      | ALTER TABLE
gba-postgres-1      | CREATE TABLE
gba-postgres-1      | ALTER TABLE
gba-postgres-1      | CREATE SEQUENCE
gba-postgres-1      | ALTER TABLE
gba-postgres-1      | CREATE TABLE
gba-postgres-1      | ALTER TABLE
gba-postgres-1      | CREATE SEQUENCE
gba-postgres-1      | ALTER TABLE
gba-postgres-1      | CREATE TABLE
gba-postgres-1      | ALTER TABLE
gba-postgres-1      | CREATE TABLE
gba-postgres-1      | ALTER TABLE
gba-postgres-1      | CREATE SEQUENCE
gba-postgres-1      | ALTER TABLE
gba-postgres-1      | CREATE TABLE
gba-postgres-1      | ALTER TABLE
gba-postgres-1      | INSERT 0 1
gba-postgres-1      | INSERT 0 1
gba-postgres-1      | INSERT 0 1
gba-postgres-1      | INSERT 0 1
gba-postgres-1      | INSERT 0 1
gba-postgres-1      | INSERT 0 1
gba-postgres-1      | INSERT 0 1
gba-postgres-1      | INSERT 0 1
gba-postgres-1      | INSERT 0 1
gba-postgres-1      | INSERT 0 1
gba-postgres-1      | INSERT 0 1
gba-postgres-1      | INSERT 0 1
gba-postgres-1      | INSERT 0 1
gba-postgres-1      | INSERT 0 1
gba-postgres-1      | INSERT 0 1
gba-postgres-1      | INSERT 0 1
gba-postgres-1      | INSERT 0 1
gba-postgres-1      | INSERT 0 1
gba-postgres-1      | INSERT 0 1
gba-postgres-1      | INSERT 0 1
gba-postgres-1      | INSERT 0 1
gba-postgres-1      | INSERT 0 1
gba-postgres-1      | INSERT 0 1
gba-postgres-1      | INSERT 0 1
gba-postgres-1      | INSERT 0 1
gba-postgres-1      | INSERT 0 1
gba-postgres-1      | INSERT 0 1
gba-postgres-1      | INSERT 0 1
gba-postgres-1      | INSERT 0 1
gba-postgres-1      | INSERT 0 1
gba-postgres-1      |  setval
gba-postgres-1      | --------
gba-postgres-1      |      11
gba-postgres-1      | (1 row)
gba-postgres-1      |
gba-postgres-1      |  setval
gba-postgres-1      | --------
gba-postgres-1      |       1
gba-postgres-1      | (1 row)
gba-postgres-1      |
gba-postgres-1      |  setval
gba-postgres-1      | --------
gba-postgres-1      |       9
gba-postgres-1      | (1 row)
gba-postgres-1      |
gba-postgres-1      |  setval
gba-postgres-1      | --------
gba-postgres-1      |       2
gba-postgres-1      | (1 row)
gba-postgres-1      |
gba-postgres-1      |  setval
gba-postgres-1      | --------
gba-postgres-1      |       1
gba-postgres-1      | (1 row)
gba-postgres-1      |
gba-postgres-1      |  setval
gba-postgres-1      | --------
gba-postgres-1      |       1
gba-postgres-1      | (1 row)
gba-postgres-1      |
gba-postgres-1      |  setval
gba-postgres-1      | --------
gba-postgres-1      |       2
gba-postgres-1      | (1 row)
gba-postgres-1      |
gba-postgres-1      | ALTER TABLE
gba-postgres-1      | ALTER TABLE
gba-postgres-1      | ALTER TABLE
gba-postgres-1      | ALTER TABLE
gba-postgres-1      | ALTER TABLE
gba-postgres-1      | ALTER TABLE
gba-postgres-1      | ALTER TABLE
gba-postgres-1      | REVOKE
gba-postgres-1      | GRANT
gba-postgres-1      | GRANT
gba-postgres-1      |
gba-postgres-1      |
gba-postgres-1      | /usr/local/bin/docker-entrypoint.sh: running /docker-entrypoint-initdb.d/init_gbajs3_db.sql
gba-postgres-1      | SET
gba-postgres-1      | SET
gba-postgres-1      | SET
gba-postgres-1      | SET
gba-postgres-1      | SET
gba-postgres-1      |  set_config
gba-postgres-1      | ------------
gba-postgres-1      |
gba-postgres-1      | (1 row)
gba-postgres-1      |
gba-postgres-1      | SET
gba-postgres-1      | SET
gba-postgres-1      | SET
gba-postgres-1      | SET
gba-postgres-1      | CREATE DATABASE
gba-postgres-1      | ALTER DATABASE
gba-postgres-1      | You are now connected to database "gbajs3" as user "postgres".
gba-postgres-1      | SET
gba-postgres-1      | SET
gba-postgres-1      | SET
gba-postgres-1      | SET
gba-postgres-1      | SET
gba-postgres-1      |  set_config
gba-postgres-1      | ------------
gba-postgres-1      |
gba-postgres-1      | (1 row)
gba-postgres-1      |
gba-postgres-1      | SET
gba-postgres-1      | SET
gba-postgres-1      | SET
gba-postgres-1      | SET
gba-postgres-1      | CREATE EXTENSION
gba-postgres-1      | COMMENT
gba-postgres-1      |
gba-postgres-1      |
gba-postgres-1      | waiting for server to shut down...2024-04-19 01:13:42.920 UTC [37] LOG:  received fast shutdown request
gba-postgres-1      | .2024-04-19 01:13:42.923 UTC [37] LOG:  aborting any active transactions
gba-postgres-1      | 2024-04-19 01:13:42.926 UTC [37] LOG:  background worker "logical replication launcher" (PID 43) exited with exit code 1
gba-postgres-1      | 2024-04-19 01:13:42.926 UTC [38] LOG:  shutting down
gba-postgres-1      | 2024-04-19 01:13:42.928 UTC [38] LOG:  checkpoint starting: shutdown immediate
gba-postgres-1      | 2024-04-19 01:13:42.993 UTC [38] LOG:  checkpoint complete: wrote 1862 buffers (11.4%); 0 WAL file(s) added, 0 removed, 0 recycled; write=0.041 s, sync=0.019 s, total=0.067 s; sync files=513, longest=0.003 s, average=0.001 s; distance=8660 kB, estimate=8660 kB
gba-postgres-1      | 2024-04-19 01:13:43.004 UTC [37] LOG:  database system is shut down
gba-postgres-1      |  done
gba-postgres-1      | server stopped
gba-postgres-1      |
gba-postgres-1      | PostgreSQL init process complete; ready for start up.
gba-postgres-1      |
gba-postgres-1      | 2024-04-19 01:13:43.045 UTC [1] LOG:  starting PostgreSQL 15.2 on x86_64-pc-linux-musl, compiled by gcc (Alpine 12.2.1_git20220924-r4) 12.2.1 20220924, 64-bit
gba-postgres-1      | 2024-04-19 01:13:43.046 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
gba-postgres-1      | 2024-04-19 01:13:43.046 UTC [1] LOG:  listening on IPv6 address "::", port 5432
gba-postgres-1      | 2024-04-19 01:13:43.049 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
gba-postgres-1      | 2024-04-19 01:13:43.054 UTC [58] LOG:  database system was shut down at 2024-04-19 01:13:42 UTC
gba-postgres-1      | 2024-04-19 01:13:43.093 UTC [1] LOG:  database system is ready to accept connections
gba-admin-server-1  | 检查 pg 配置 user=postgres password=postgres dbname=goadmin host=gba-postgres port=5432 sslmode=disable
gba-admin-server-1  | 检查 pg 配置 user=postgres password=postgres dbname=gbajs3 host=gba-postgres port=5432 sslmode=disable
gba-auth-server-1   | 2024/04/19 01:13:51 gbajs3 auth server started
gba-auth-server-1 exited with code 1
webserver-1         | /entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration
webserver-1         | /entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
webserver-1         | /entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
webserver-1         | 10-listen-on-ipv6-by-default.sh: info: Getting the checksum of /etc/nginx/conf.d/default.conf
webserver-1         | 10-listen-on-ipv6-by-default.sh: info: Enabled listen on IPv6 in /etc/nginx/conf.d/default.conf
webserver-1         | /entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh
webserver-1         | 20-envsubst-on-templates.sh: Running envsubst on /etc/nginx/templates/nginx.conf.template to /etc/nginx/conf.d/nginx.conf
webserver-1         | /entrypoint.sh: Launching /docker-entrypoint.d/30-tune-worker-processes.sh
webserver-1         | /entrypoint.sh: Configuration complete; ready for start up
webserver-1         | /entrypoint.sh: Configuring syslog and fail2ban
webserver-1         | rsyslogd: imklog: cannot open kernel log (/proc/kmsg): Operation not permitted.
webserver-1         | rsyslogd: activation of module imklog failed [v8.2212.0 try https://www.rsyslog.com/e/2145 ]
webserver-1         | 2024/04/19 01:13:52 [emerg] 1#1: host not found in upstream "gba-auth-server:443" in /etc/nginx/conf.d/nginx.conf:6
webserver-1         | nginx: [emerg] host not found in upstream "gba-auth-server:443" in /etc/nginx/conf.d/nginx.conf:6
webserver-1 exited with code 1

It finally got to here, it was failing previously because I didnt name the rom folders correctly. Now I'm having this issue? Its likely because I dont have SSL certs, any ideas?

**Comment by thenick775** [comment]
Your auth server isn't alive, it's exiting causing the nginx proxy to error out when looking for an upstream server.

This is most likely the missing  ssl cert/key.

I would have expected it to print `handling requests initiated`, so it could be something else, but that's my best guess without more info.

I'd try generating some self signed certificates, either on your machine using the openssl command featured in the readme, or through another method. If they're self signed the server will boot, but no guarantee if this will work without you having to navigate through an insecure network page in your browser (shouldn't be a big deal if you don't care about that). I will note anything touching the service worker/PWA infrastructure won't work without ssl.

But that will at least get you to a point where you can investigate using zerossl for proper certs, or until I have time to consider making ssl optional in the auth server.

**Comment by thenick775** [comment]
Hey @7v5, I've added a workflow item that can be manually triggered to deploy the frontend to GitHub Pages.

It can be found in the action tab, and is named `Deploy Staging` which requires a manual trigger.

I'm calling this my staging environment, as I was sorely in need of one. Currently, the yaml I built does not support passing in the environment variable `VITE_GBA_SERVER_LOCATION` to specify where you're hosting your backend.

That should only entail some GitHub configuration and modifying the yaml [here](https://github.com/thenick775/gbajs3/blob/master/.github/workflows/deploy-pages.workflow.yml) to pass in the environment variable specified above.
 
 This shouldn't be hard to add, and I do plan on doing that in the near future 😎 
 
 That should satisfy the original ask in this ticket of easy hosting on GHP.
 
 I'll also play around with the idea of using GitHub actions to automate the deploys to AWS using this [action](https://github.com/marketplace/actions/deploy-docker-to-aws-ec2), and maybe a few other hosting providers, but that will depend on what's available and what I can easily build out.
 
 Feel free to keep commenting here if your still having trouble with your self hosted setup, or open a discussion if you need any additional assistance!
