### ISSUE TITLE
Download all types of files in file system

### ISSUE THREAD

**Issue by henry753951** [thenick775/gbajs3#84]
Can download all types of files (like .ss0 state) instead of just .sav

**Comment by thenick775** [comment]
There's currently no mechanism for this at the moment, but this is a great enhancement, and will now be implemented soon 😎 

Thanks for opening this issue!

**Comment by thenick775** [comment]
Hello, you can now download any file present within the file system using the cloud download icon shown below:

<img width="296" alt="Screenshot 2024-04-18 at 8 06 47 PM" src="https://github.com/thenick775/gbajs3/assets/40526638/f5a018b4-b505-4833-a03a-a9672aafd06d">

Thanks again for bringing this to my attention, and feel free to comment here if this doesn't suit your needs! 😎
