### ISSUE TITLE
Why do I close the game after selecting it on the page? I can't see my game in Select Local Rom

### ISSUE THREAD

**Issue by PeachByMilk** [thenick775/gbajs3#94]
![image](https://github.com/thenick775/gbajs3/assets/52044483/bdd3bf95-f2cf-49cf-98c6-5b966cfe343a)

**Comment by thenick775** [comment]
See my response [here](https://github.com/thenick775/gbajs3/issues/34#issuecomment-1868171537) for details with screenshots.

In short, you need to save your file system after loading your save files/rom files for them to be persisted to your indexed db storage to be selectable after you reload the page.

**Comment by PeachByMilk** [comment]
When modifying React code to access FileSystemFile, I encountered error code 44, which only appears during the first execution. This could stem from permission issues or incorrect initialization of the file system API. How can I resolve this?

**Comment by PeachByMilk** [comment]
` 
  const handleCreateState = () => {
    if (!emulator) {
      console.error('Emulator is not initialized');
      return;
    }

    if (isEmulatorRunning) {
      emulator.fsSync()
        .then(() => {
          // 确认路径存在
          if (!emulator.filePaths().saveStatePath) {
            console.error('Save state path is undefined.');
            return Promise.reject('Save state path is undefined.');
          }
          emulator.createSaveState(currentSlot + 1);
          return emulator.listSaveStates();
        })
        .then(() => {
          setCurrentSlot(currentSlot + 1);

          const gameName = emulator.getCurrentGameName() || 'unknown';
          const gameNameWithoutExtension = gameName.split('.')[0];
          const stateFileName = `${gameNameWithoutExtension}.ss${currentSlot}`;
          const saveStatePath = `${emulator.filePaths().saveStatePath}/${stateFileName}`;

          try {
            const saveStateFile = emulator.getFile(saveStatePath);
            if (!saveStateFile) {
              console.error('Failed to get save saveStateFile:', saveStatePath);
              return;
            }
          } catch (error) {
            console.error('Failed to get save state file:', error);
            return;
          }
          const saveStateFile = emulator.getFile(saveStatePath);

          const saveFile = new Blob([saveStateFile], { type: 'application/octet-stream' });
          const reader = new FileReader();

          reader.onloadend = function() {
            const base64SaveFileBytes = reader.result as string;
            const base64Data = base64SaveFileBytes.split(',')[1];
            
          };

          reader.readAsDataURL(saveFile);
        })
        .catch(error => {
          console.error('Error during save state process:', error);
        });
    }
  };

`

this is my code, when i get stateFile,error:[Failed to get save state file: ErrnoError errno: 44 name: "ErrnoError"]

**Comment by thenick775** [comment]
In the code you have shown here, I cannot see how your initializing the emulator.

Are you calling `FSInit` like I do in this [code](https://github.com/thenick775/gbajs3/blob/master/gbajs3/src/hooks/use-emulator.tsx#L21)?

You may have to wait for the promise returned to complete, meaning the FSInit has completed and made the required directories in the IDBFS storage layer.

You can see I await [here](https://github.com/thenick775/gbajs3/blob/master/gbajs3/src/hooks/use-emulator.tsx#L21) but also don't set the emulator state until the emulator is marked fully ready.

Some other info: 
- your file system will have the save state without calling FSSync, this is only needed if you want to copy your file system to indexed db
- errorno 44 is the equivalent of ENOENT, meaning the file system can't find the file at the path your seeing.

**Comment by thenick775** [comment]
> ```js
>         .then(() => {
>           setCurrentSlot(currentSlot + 1);
> 
>           const gameName = emulator.getCurrentGameName() || 'unknown';
>           const gameNameWithoutExtension = gameName.split('.')[0];
>           const stateFileName = `${gameNameWithoutExtension}.ss${currentSlot}`;
>           const saveStatePath = `${emulator.filePaths().saveStatePath}/${stateFileName}`;

This piece of code is also potentially problematic.

In react, the state updates on the next render, or when its batch updated by the react internals.

I do not know for sure if this is what your problem is, but the value you are using in  `stateFileName` may be stale.

I would potentially rewrite the code as follows:
```js
// generates save state,
// fetches it from emulator file system,
// and then downloads it as a file
const handleCreateState = () => {
  if (!emulator) {
    console.error('Emulator is not initialized');
    return;
  }

  const localCurrentSlot = currentSlot + 1;

  emulator.createSaveState(localCurrentSlot);

  const gameName = emulator.getCurrentGameName() || 'unknown.gba';
  const gameNameWithoutExtension = gameName.split('.')[0];
  const saveStateFileName = `${gameNameWithoutExtension}.ss${localCurrentSlot}`;

  const saveStatePath = `${
    emulator.filePaths().saveStatePath
  }/${saveStateFileName}`;

  const file = emulator?.getFile(saveStatePath);

  if (file) {
    const fileDownload = new Blob([file], {
      type: 'data:application/octet-stream',
    });

    const link = document.createElement('a');
    link.download = saveStateFileName;
    link.href = URL.createObjectURL(fileDownload);
    link.click();
    link.remove();
  }
};
```

**Comment by PeachByMilk** [comment]
Thank you so much for your detailed explanation! Following your advice, I reconfigured the initialization process and adjusted the logic for state updates. Everything is working perfectly now, and the issue has been resolved. Thank you again for your time and assistance; it was incredibly helpful!
